name: Release

on:
  push:
    tags:
      - "v*"

env:
  ReleaseFileName: MozaPlugin_${{ github.ref_name }}.zip

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv -l -s all
        env:
          OUTPUT: CHANGES.md

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Extract version from tag
        id: version
        shell: bash
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugin DLL
        run: dotnet build -c Release --no-restore /p:Version=${{ steps.version.outputs.version }}

      - name: Zip output DLL
        run: Compress-Archive -Path ./bin/x86/Release/MozaPlugin.dll -DestinationPath ./${{ env.ReleaseFileName }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: ${{ env.ReleaseFileName }}

  create-release:
    runs-on: ubuntu-latest
    needs:
      - generate-changelog
      - build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-file

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: "${{ needs.generate-changelog.outputs.release_body }}"
          fail_on_unmatched_files: true
          files: ${{ env.ReleaseFileName }}
